Veoss 1430 | Realign with EuReg Frontend changes
hmrc/one-stop-shop-registration pull request #104
Opened 2023-02-22 14:33 UTC by warrenskiwork1979

2023-03-02 16:02 UTC, DevAndyroo requested changes

2023-03-02 16:02 UTC, DevAndyroo commented on test/crypto/RegistrationEncrypterSpec.scala
> +//    "must encrypt an EU VAT Registration and decrypt it" in {
uncomment and fix test if needs fixing

2023-03-02 17:26 UTC, warrenskiwork1979 commented on test/crypto/RegistrationEncrypterSpec.scala
> +//    "must encrypt an EU VAT Registration and decrypt it" in {
Uncommented and fixed

2023-03-06 09:43 UTC, DevAndyroo approved these changes

2023-03-06 09:44 UTC, merged